apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wounds-server
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/datasci4citizens/server-infrastructure.git
    targetRevision: main
    path: apps/wounds-server/overlays/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: wounds-server
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
