apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: mih-server

resources:
  - ../../base
  - secret.yaml

# Override image tag via CI/CD or manually
images:
  - name: ghcr.io/luizlenharo/server-mih
    newTag: latest
